dracor-org/dracor-api

data.xconf, jobs/sitelinks.xq, modules/api.xqm, modules/config.xqm, modules/load.xqm, modules/metrics.xqm, modules/util.xqm, post-install.xq, pre-install.xq
=> Change paths

api.yaml, build.xml, modules/api.xqm
=> Load corpus with POST request

jobs/process-webhook-delivery.xq, modules/webhook.xqm
=> Use GitHub data API for webhook updates

modules/api.xqm, modules/util.xqm
=> Properly output DraCor IDs in 'id' attributes

modules/rdf.xqm
reworked module to generate RDF per play. Added metrics and characters.
=> Feature cidocrdf

api.yaml, modules/api.xqm, modules/util.xqm
This PR adds relation data (if available) to the play info and provides the data in CSV and GEXF.
Resolves #90.
=> Expose relation data

modules/api.xqm
=> Fix CSV output for cast info

api.yaml, modules/api.xqm
=> GraphML for relations

modules/api.xqm, modules/wikidata.xqm
=> Implement endpoint /author/{wikidata-id}

modules/api.xqm, modules/util.xqm
This PR is meant to resolve #118 and may also be a solution for #150.
=> Provide English name or title variants where available

api.yaml, modules/api.xqm, modules/util.xqm
=> Implement endpoint /character/{id}

modules/api.xqm, modules/metrics.xqm, modules/rdf.xqm, modules/util.xqm
These changes adapt the utility functions to schema changes of dracor-org/dracor-schema#38.
=> Adjust to schema changes introducing standOff

modules/util.xqm
=> Normalize pubPlace for output

modules/rdf.xqm
=> Don't add owl:sameAs if play has no Wikidata ID

.dockerignore, .existdb.json.tmpl, .gitignore, README.md, build.properties, compose.yml, data.xconf, jobs/load-corpus.xq, jobs/process-webhook-delivery.xq, jobs/sitelinks.xq, modules/api.xqm, modules/config.xqm, modules/load.xqm, modules/metrics.xqm, modules/rdf.xqm, modules/trigger.xqm, modules/util.xqm, modules/webhook.xqm, modules/wikidata.xqm, post-install.xq, pre-install.xq, repo.xml, speakers.xq
This PR introduces a version prefix `/v0` to all endpoints and adds a version part to name space URIs. This will allow us to install different major versions of the dracor-api  extension into the same eXist DB.
=> Prepare API for versioning

api.yaml, modules/api.xqm, modules/wikidata.xqm
=> Implement /wikidata/mixnmatch

api.yaml, modules/api.xqm, modules/util.xqm
=> Rename `cast` to `characters`

modules/api.xqm, modules/metrics.xqm, modules/trigger.xqm, modules/util.xqm
=> Update Wikipedia link count on play ingest

api.yaml
=> Add 'x-dracor-feature' property to api.yaml

modules/wikidata.xqm
Wikidata now seems to enforce their [robot policy](https://wikitech.wikimedia.org/wiki/Robot_policy) which requires service to identify their user agent. Since the DraCor API did not do so its wikidata queries started to receive 403 responses with the message
> Please set a user-agent and respect our robot policy https://w.wiki/4wJS. See also T400119.
This PR mitigates the problem.
fixes dracor-org/dracor-frontend#353
=> Add User-Agent header to wikidata queries
